language: python
python:
  - "3.5"
env:
  - DJANGO=1.10
install:
  - pip install -r requirements.txt
  - pip install pep8
#before_script:
#  - "pep8 --exclude=migrations --ignore=E501,E225 monitor"
script:
  - python manage.py test -v 3
notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    on_success: change
    on_failure: change
    channels:
      - "chat.freenode.net#linaro-qa"
