# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lava_server', models.URLField()),
                ('lava_job_id', models.CharField(max_length=16)),
                ('lava_job_status', models.CharField(blank=True, max_length=16, null=True)),
                ('build_job_name', models.CharField(max_length=1024)),
                ('build_job_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
