# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='lava_job_status',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='lava_server',
            field=models.URLField(),
        ),
    ]
