# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pattern_build_job_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='build_job_url',
            field=models.URLField(),
        ),
    ]
