# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170203_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=1024)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
