# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LavaListener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('publisher_address', models.CharField(max_length=1024)),
                ('topic_name', models.CharField(max_length=1024)),
                ('pid', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
