# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavalistener',
            name='status',
        ),
    ]
