# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0002_remove_lavalistener_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavalistener',
            name='pid',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
