# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listener', '0003_auto_20170125_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LavaListener',
        ),
    ]
